#define TAPPING_TERM 115
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD

#define TAP_CODE_DELAY 5
#define COMBO_TERM 50

#pragma once
#define VIAL_KEYBOARD_UID {0xBC, 0x17, 0xE9, 0x5D, 0x00, 0x9A, 0x4C, 0xC8}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 9 }
