name: On-Push Compile

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  list-keymaps:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list-keymaps.outputs.matrix }}
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: List Keymaps
        id: list-keymaps
        run: |
          python -c "import os,json; print('matrix='+json.dumps({'include': [{'keymap': d} for d in os.listdir('keymaps') if os.path.isdir(os.path.join('keymaps', d))]}))" >> $GITHUB_OUTPUT
  compile:
    needs: list-keymaps
    strategy:
      matrix: ${{fromJson(needs.list-keymaps.outputs.matrix)}}
    permissions:
      contents: read
    uses: ./.github/workflows/compile-firmware-workflow-call.yaml
    with:
      git-ref: ${{ github.ref }}
      keymap: ${{ matrix.keymap }}
