name: Upload Assets On Release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/compile-firmware-workflow-call.yaml
    with:
      git-ref: ${{ github.ref }}
      keymap: "vial"
    permissions:
      contents: read
  up:
    needs: [build]
    if: ${{ success() }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: hmproto34s-vial
          path: artifacts
      - name: Upload Release Asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$GITHUB_REF_NAME" ./artifacts/hmproto34_default.hex --repo "$GITHUB_REPOSITORY" --clobber
