name: Upload Assets On Release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/compile-firmware-workflow-call.yaml
    with:
      git-ref: ${{ github.ref }}
      keymap: "vial"
  up:
    needs: [build]
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: hmproto34s-vial
          path: artifacts
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/hmproto34s_vial.hex
          asset_name: hmproto34s_vial.hex
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
