name: Validate Version

# TODO: restrict inputs.tag to be a tag

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  validate_version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      - name: Check Version
        run: |
          # Check if the tag is the same as the version in info.json
          export tag=$(echo "$INPUTS_TAG" | cut -d / -f 3)
          echo "extracted tag: $tag"
          grep "\"device_version\": \"$tag\"" info.json || (echo "Version mismatch" && exit 1)
        env:
          INPUTS_TAG: ${{ inputs.tag }}
